using System.Collections.Generic;

namespace Glacie.Testing
{
    internal sealed class GrimDawnProfile
    {
        private static readonly string[] _knownArcFiles =
        {
            "database/templates.arc",
            "resources/Conversations.arc",
            "resources/Creatures.arc",
            "resources/Fonts.arc",
            "resources/FX.arc",
            "resources/Items.arc",
            "resources/Level Art.arc",
            "resources/Levels.arc",
            "resources/Menu.arc",
            "resources/Quests.arc",
            "resources/Scripts.arc",
            "resources/Shaders.arc",
            "resources/Sound.arc",
            "resources/System.arc",
            "resources/Terrain Textures.arc",
            "resources/Text_EN.arc",
            "resources/UI.arc",
            "gdx1/resources/Conversations.arc",
            "gdx1/resources/Creatures.arc",
            "gdx1/resources/FX.arc",
            "gdx1/resources/Items.arc",
            "gdx1/resources/Level Art.arc",
            "gdx1/resources/Levels.arc",
            "gdx1/resources/Quests.arc",
            "gdx1/resources/Scripts.arc",
            "gdx1/resources/Sound.arc",
            "gdx1/resources/Terrain Textures.arc",
            "gdx1/resources/Text_EN.arc",
            "gdx1/resources/UI.arc",
            "gdx2/resources/Conversations.arc",
            "gdx2/resources/Creatures.arc",
            "gdx2/resources/FX.arc",
            "gdx2/resources/Items.arc",
            "gdx2/resources/Level Art.arc",
            "gdx2/resources/Levels.arc",
            "gdx2/resources/Quests.arc",
            "gdx2/resources/Scripts.arc",
            "gdx2/resources/Sound.arc",
            "gdx2/resources/System.arc",
            "gdx2/resources/Terrain Textures.arc",
            "gdx2/resources/Text_EN.arc",
            "gdx2/resources/UI.arc",
            "mods/survivalmode/resources/Conversations.arc",
            "mods/survivalmode/resources/Creatures.arc",
            "mods/survivalmode/resources/FX.arc",
            "mods/survivalmode/resources/Items.arc",
            "mods/survivalmode/resources/Level Art.arc",
            "mods/survivalmode/resources/Maps.arc",
            "mods/survivalmode/resources/Scripts.arc",
            "mods/survivalmode/resources/Sounds.arc",
            "mods/survivalmode/resources/Text_EN.arc",
            "mods/survivalmode/resources/UI.arc",
            "survivalmode1/resources/Conversations.arc",
            "survivalmode1/resources/Maps.arc",
            "survivalmode1/resources/Scripts.arc",
            "survivalmode1/resources/Sounds.arc",
            "survivalmode1/resources/Text_EN.arc",
            "survivalmode2/resources/conversations.arc",
            "survivalmode2/resources/maps.arc",
            "survivalmode2/resources/scripts.arc",
            "survivalmode2/resources/text_en.arc",
        };

        public IReadOnlyCollection<string> GetKnownArcFiles() => _knownArcFiles;
    }
}
